#!/bin/bash

python create_sw_tf_record.py \
    --label_map_path=/Users/gsq/Desktop/Alex_Vild/Variant-ViLD/[6]-Transfer-Learning-eg/lab-1/object_detection_self/data/sw_label_map.pbtxt \
    --data_dir=/Users/gsq/Desktop/Alex_Vild/Variant-ViLD/[6]-Transfer-Learning-eg/lab-1 \
    --output_dir=/Users/gsq/Desktop/Alex_Vild/Variant-ViLD/[6]-Transfer-Learning-eg/lab-1/object_detection_self/data \
