#!/bin/bash
rm -rf train/output_inference_graph.pb

python3 ../models/research/object_detection/export_inference_graph.py \
    --input_type image_tensor \
    --pipeline_config_path /Users/gsq/Desktop/Alex_Vild/Variant-ViLD/[6]-Transfer-Learning-eg/lab-1/object_detection_self/data/ssd_inception_v2_pets.config \
    --trained_checkpoint_prefix train/model.ckpt-5533 \
    --output_directory train/output_inference_graph.pb \