image_path: "./run_demo/Example/SH_2.png" #Path to image
min_box_area: 1200
label_path: "./run_demo/label/sh_label.txt" #Path to label
save_path: "./run_demo/demo_result" #Path to save result

prompt_engineering: True #Use prompt engineering
this_is: True #Use 'this is' in labeling
temperature: 100.0
use_softmax: False
run_on_gpu: False

saved_model_dir: "./save_models/" #dir of the saved models
nms_threshold: 0.4 #nms threshold
min_rpn_score_thresh: 0.7
max_boxes_to_draw: 100
